### ISSUE TITLE
NL ING not working

### ISSUE THREAD

**Issue by fullastern** [torbengb/bank2ynab#206]
*Dear submitter, please edit the following according to your needs. Thank you!*

**Describe the bug**
When running bank2ynab with a NL ING CSV file the following output is shown

root@kali:~/Desktop/bank2ynab-master# python3 bank2ynab.py

Parsing input file:  /root/Desktop/bank2ynab-master/NL**INGB**_01-02-2018_09-05-2018.csv
Parsed 0 lines
Writing output file: /root/Desktop/bank2ynab-master/fixed_NL**INGB**_01-02-2018_09-05-2018.csv

Done! 1 files processed.

**What did you EXPECT to happen?**
A fixed CSV file with the converted data.

**What ACTUALLY happened?**
Only the headers are written to the output file.

**What did you DO? (steps to reproduce)**
1. Downloaded CSV file
2. Run the program

**What's your software environment?**
 - Script language: tried with python 2.7 and 3.6.5
 - Operating system: tried both on Windows 7 and Kali Linux (Debian)

**Can you provide other helpful information?**
See attached CSV file

[NL..INGB.........._01-02-2018_09-05-2018.txt](https://github.com/torbengb/bank2ynab/files/1993204/NL.INGB._01-02-2018_09-05-2018.txt)

**Attachments**
If applicable, add sample files or screenshots to help explain your problem.

**Comment by toyg** [comment]
Multiple issues here, thanks for your file.

1. open bank2ynab.conf in a text editor (like notepad) and search for the section [NL ING]. In that section, there is a line:
`Input Columns = Date,Payee,skip,skip,skip,CDFlag,Amount,skip,Memo`
change it to
`Input Columns = Date,Payee,skip,skip,skip,CDFlag,Inflow,skip,Memo`
That's a bug and will get fixed asap.

2. the configuration expects filenames like "NL12INGB123456789_12_12_2012_12_12_2012". I don't know if that's correct, but basically make sure the number of digits matches.

**Comment by nocalla** [comment]
Thanks for reporting, fixing now.

**Comment by fullastern** [comment]
root@kali:~/Desktop/bank2ynab-master# python3 bank2ynab.py

Parsing input file:  /root/Desktop/bank2ynab-master/NL12INGB123456789_22_02_2018_12_05_2018.csv
Traceback (most recent call last):
  File "bank2ynab.py", line 533, in <module>
    b2y.run()
  File "bank2ynab.py", line 521, in run
    output = bank.read_data(original_file_path)
  File "bank2ynab.py", line 375, in read_data
    row = self._cd_flag_process(row)
  File "bank2ynab.py", line 461, in _cd_flag_process
    row[inflow_col] = str(-1 * float(row[inflow_col]))
ValueError: could not convert string to float: '7,05'

**Comment by nocalla** [comment]
Okay that's a bug from #207! Not a particular bug for this bank, it's a problem with how numbers are handled.

**Comment by toyg** [comment]
Yep, that’s how I noticed it 😉

**Comment by nocalla** [comment]
Fixes #207, so hopefully this should work now @fullastern.

**Comment by fullastern** [comment]
still not working.

root@kali:~/bank2ynab# python3 bank2ynab.py 

Parsing input file:  /root/bank2ynab/NL12INGB123456789_12_12_2012_12_12_2012.csv.csv
Traceback (most recent call last):
  File "bank2ynab.py", line 552, in <module>
    b2y.run()
  File "bank2ynab.py", line 540, in run
    output = bank.read_data(original_file_path)
  File "bank2ynab.py", line 382, in read_data
    row = self._cd_flag_process(row)
  File "bank2ynab.py", line 468, in _cd_flag_process
    outflow_col = self.config["input_columns"].index("Outflow")
ValueError: 'Outflow' is not in list

**Comment by nocalla** [comment]
Ah, my fault. A bug in my bugfix! Thanks for your persistence. I'll fix
this later on today.

**Comment by nocalla** [comment]
@fullastern - I've just pushed a commit addressing this. Would you mind testing with your file again please?

**Comment by nocalla** [comment]
I fixed the issue causing this problem, so closing for now, so I don't have a big BUG label looking at me the whole time. Will reopen if it's still occurring.
